/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface CoreSettings {
  createdAt: Generated<Timestamp>;
  defaultCurrency: Generated<string>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  updatedAt: Generated<Timestamp>;
  weekStartDay: Generated<number>;
}

export interface FinanceAccounts {
  createdAt: Generated<Timestamp>;
  currency: Generated<string>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  name: string;
  openingBalance: Generated<Numeric>;
  sortOrder: Generated<number>;
  type: string;
  updatedAt: Generated<Timestamp>;
}

export interface FinanceBudgetItemOverrides {
  amount: Numeric;
  budgetItemVersionId: string;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  month: string;
  updatedAt: Generated<Timestamp>;
}

export interface FinanceBudgetItems {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  section: string;
  updatedAt: Generated<Timestamp>;
}

export interface FinanceBudgetItemVersions {
  amount: Numeric | null;
  anchor: string;
  budgetItemId: string;
  cadence: string;
  cadenceDate: string | null;
  cadenceMonth: number | null;
  carryToItemId: string | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  name: string;
  onReset: string | null;
  parentItemId: string | null;
  percent: Numeric | null;
  percentBase: Generated<string>;
  planVersionId: string;
  resetCycle: string | null;
  rollover: Generated<boolean>;
  sortOrder: Generated<number>;
  updatedAt: Generated<Timestamp>;
}

export interface FinanceBudgetPlanVersions {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  effectiveFromMonth: string;
  id: Generated<string>;
  note: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface FinanceBudgetTransfers {
  amount: Numeric;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  fromItemId: string;
  id: Generated<string>;
  kind: Generated<string>;
  note: string | null;
  occurredAt: string | null;
  occurredOn: string;
  toItemId: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface FinanceCategories {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  name: string;
  parentId: string | null;
  sortOrder: Generated<number>;
  updatedAt: Generated<Timestamp>;
}

export interface FinanceRecordLines {
  amount: Numeric;
  budgetItemId: string | null;
  categoryId: string | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  fxRate: Numeric | null;
  id: Generated<string>;
  note: string | null;
  recordId: string;
  sortOrder: Generated<number>;
  twdAmount: Numeric;
  updatedAt: Generated<Timestamp>;
}

export interface FinanceRecords {
  accountId: string;
  counterAccountId: string | null;
  counterAmount: Numeric | null;
  createdAt: Generated<Timestamp>;
  currency: Generated<string>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  note: string | null;
  occurredAt: string | null;
  occurredOn: string;
  targetBalance: Numeric | null;
  type: string;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  "core.settings": CoreSettings;
  "finance.accounts": FinanceAccounts;
  "finance.budgetItemOverrides": FinanceBudgetItemOverrides;
  "finance.budgetItems": FinanceBudgetItems;
  "finance.budgetItemVersions": FinanceBudgetItemVersions;
  "finance.budgetPlanVersions": FinanceBudgetPlanVersions;
  "finance.budgetTransfers": FinanceBudgetTransfers;
  "finance.categories": FinanceCategories;
  "finance.recordLines": FinanceRecordLines;
  "finance.records": FinanceRecords;
}
